baseURL: 'http://localhost:1313/'
languageCode: en
defaultContentLanguage: zh-cn
title: Mehameha
preserveTaxonomyNames: true
enableRobotsTXT: true
enableEmoji: true
theme: even
enableGitInfo: false
pygmentsOptions: linenos=table
pygmentsCodefences: true
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
hasCJKLanguage: true
paginate: 10
disqusShortname: ''
googleAnalytics: ''
copyright: ''
author:
  name: Scott
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
menu:
  main:
    - name: 主页
      weight: 10
      identifier: home
      url: /
    - name: 归档
      weight: 20
      identifier: archives
      url: /post/
    - name: 标签
      weight: 30
      identifier: tags
      url: /tags/
    - name: 关于
      weight: 40
      identifier: about
      url: /about
params:
  version: 4.x
  debug: false
  since: '2018'
  gitRepo: ''
  logoTitle: 自省
  keywords:
    - Java
    - 分布式
    - 数据
  description: 博客主要记录个人学习与工作的经验，以及所思所想
  archivePaginate: 20
  showArchiveCount: true
  dateFormatToUse: '2006-01-02'
  moreMeta: true
  highlightInClient: false
  toc: true
  autoCollapseToc: false
  fancybox: true
  mathjax: true
  mathjaxEnableSingleDollar: true
  mathjaxEnableAutoNumber: false
  mathjaxUseLocalFiles: false
  postMetaInFooter: false
  linkToMarkDown: false
  contentCopyright: ''
  changyanAppid: ''
  changyanAppkey: ''
  livereUID: ''
  baiduPush: false
  baiduAnalytics: ''
  baiduVerification: ''
  googleVerification: ''
  customCSS: []
  customJS: []
  uglyURLs: false
  publicCDN:
    enable: true
    jquery: >-
      <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>
    slideout: >-
      <script
      src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js"
      integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg="
      crossorigin="anonymous"></script>
    fancyboxJS: >-
      <script
      src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js"
      integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY="
      crossorigin="anonymous"></script>
    fancyboxCSS: >-
      <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css"
      integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY="
      crossorigin="anonymous">
    timeagoJS: >-
      <script
      src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.min.js"
      integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI="
      crossorigin="anonymous"></script>
    timeagoLocalesJS: >-
      <script
      src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.locales.min.js"
      integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8="
      crossorigin="anonymous"></script>
    flowchartDiagramsJS: >-
      <script src="https://cdn.jsdelivr.net/npm/raphael@2.2.7/raphael.min.js"
      integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI="
      crossorigin="anonymous"></script> <script
      src="https://cdn.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js"
      integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k="
      crossorigin="anonymous"></script>
    sequenceDiagramsCSS: >-
      <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.css"
      integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF"
      crossorigin="anonymous">
    sequenceDiagramsJS: >-
      <script
      src="https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js"
      integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc="
      crossorigin="anonymous"></script> <script
      src="https://cdn.jsdelivr.net/npm/snapsvg@0.5.1/dist/snap.svg-min.js"
      integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8="
      crossorigin="anonymous"></script> <script
      src="https://cdn.jsdelivr.net/npm/underscore@1.8.3/underscore-min.js"
      integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek="
      crossorigin="anonymous"></script> <script
      src="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js"
      integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP"
      crossorigin="anonymous"></script>
  outdatedInfoWarning:
    enable: false
    hint: 30
    warn: 180
  gitment:
    owner: ''
    repo: ''
    clientId: ''
    clientSecret: ''
  utterances:
    owner: ''
    repo: ''
  gitalk:
    owner: ''
    repo: ''
    clientId: ''
    clientSecret: ''
  valine:
    enable: false
    appId: 你的appId
    appKey: 你的appKey
    notify: false
    verify: false
    avatar: mm
    placeholder: 说点什么吧...
    visitor: false
  flowchartDiagrams:
    enable: false
    options: ''
  sequenceDiagrams:
    enable: false
    options: ''
  busuanzi:
    enable: false
    siteUV: true
    sitePV: true
    pagePV: true
  reward:
    enable: false
    wechat: /path/to/your/wechat-qr-code.png
    alipay: /path/to/your/alipay-qr-code.png
  social:
    a-email: 'mailto:wyf0931@sina.com'
    g-github: 'https://github.com/wyf0931'
privacy:
  googleAnalytics:
    anonymizeIP: true
  youtube:
    privacyEnhanced: true

